[workspace]
authors = ["Kutay4 <141006414+Kutay4@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "ai-supported-address-resolution"
platforms = ["osx-arm64","osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.7.1,<3"
polars = ">=1.33.0,<2"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.7.1,<2"
pandas = ">=2.3.2,<3"
transformers = ">=4.56.0,<5"
onnx = ">=1.18.0,<2"
onnxruntime = ">=1.22.0,<2"
onnxscript = ">=0.4.0,<0.5"
streamlit = ">=1.49.1,<2"
optimum = ">=1.27.0,<2"
rapidfuzz = ">=3.14.0,<4"
spacy = ">=3.8.7,<4"
faiss = ">=1.9.0,<2"
ipykernel = ">=6.30.1,<7"
